export const testUsers = [
  {
    id: 'user_001',
    firstName: 'Test',
    lastName: 'User',
    email: 'test@example.com',
    password: 'TestUser@12',
    phone: '+919876543210',
    gender: 'male',
    dob: '1990-01-01',
    newsletter: true,
    registeredAt: '2024-01-01T00:00:00Z',
    isVerified: true,
    profilePicture: null,
    addresses: [
      {
        id: 'addr_001',
        name: 'Test User',
        phone: '9876543210',
        addressLine1: '123 Test Street',
        addressLine2: 'Near Test Park',
        city: 'Bangalore',
        state: 'Karnataka',
        country: 'India',
        pincode: '560001',
        type: 'Home',
        isDefault: true,
      },
    ],
    orders: [],
    wishlist: ['prod_005', 'prod_012', 'prod_025'],
  },
  {
    id: 'user_002',
    firstName: 'Demo',
    lastName: 'Customer',
    email: 'demo@example.com',
    password: 'DemoUser@12',
    phone: '+919876543211',
    gender: 'female',
    dob: '1995-05-15',
    newsletter: false,
    registeredAt: '2024-02-15T00:00:00Z',
    isVerified: true,
    profilePicture: null,
    addresses: [
      {
        id: 'addr_002',
        name: 'Demo Customer',
        phone: '9876543211',
        addressLine1: '456 Demo Avenue',
        addressLine2: 'Block B',
        city: 'Mumbai',
        state: 'Maharashtra',
        country: 'India',
        pincode: '400001',
        type: 'Home',
        isDefault: true,
      },
    ],
    orders: [],
    wishlist: ['prod_001', 'prod_020'],
  },
];
